#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAguas.API
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaAguas")]
	public partial class SistemaAguasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertConsumo(Consumo instance);
    partial void UpdateConsumo(Consumo instance);
    partial void DeleteConsumo(Consumo instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertContador(Contador instance);
    partial void UpdateContador(Contador instance);
    partial void DeleteContador(Contador instance);
    partial void InsertFatura(Fatura instance);
    partial void UpdateFatura(Fatura instance);
    partial void DeleteFatura(Fatura instance);
    #endregion
		
		public SistemaAguasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemaAguasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemaAguasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemaAguasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Consumo> Consumos
		{
			get
			{
				return this.GetTable<Consumo>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Contador> Contadors
		{
			get
			{
				return this.GetTable<Contador>();
			}
		}
		
		public System.Data.Linq.Table<Fatura> Faturas
		{
			get
			{
				return this.GetTable<Fatura>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Consumo")]
	public partial class Consumo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _DataLeitura;
		
		private double _ValorConsumido;
		
		private double _LeituraAtual;
		
		private double _LeituraAnterior;
		
		private int _ContadorId;
		
		private EntitySet<Fatura> _Faturas;
		
		private EntityRef<Contador> _Contador;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDataLeituraChanging(System.DateTime value);
    partial void OnDataLeituraChanged();
    partial void OnValorConsumidoChanging(double value);
    partial void OnValorConsumidoChanged();
    partial void OnLeituraAtualChanging(double value);
    partial void OnLeituraAtualChanged();
    partial void OnLeituraAnteriorChanging(double value);
    partial void OnLeituraAnteriorChanged();
    partial void OnContadorIdChanging(int value);
    partial void OnContadorIdChanged();
    #endregion
		
		public Consumo()
		{
			this._Faturas = new EntitySet<Fatura>(new Action<Fatura>(this.attach_Faturas), new Action<Fatura>(this.detach_Faturas));
			this._Contador = default(EntityRef<Contador>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataLeitura", DbType="DateTime NOT NULL")]
		public System.DateTime DataLeitura
		{
			get
			{
				return this._DataLeitura;
			}
			set
			{
				if ((this._DataLeitura != value))
				{
					this.OnDataLeituraChanging(value);
					this.SendPropertyChanging();
					this._DataLeitura = value;
					this.SendPropertyChanged("DataLeitura");
					this.OnDataLeituraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorConsumido", DbType="Float NOT NULL")]
		public double ValorConsumido
		{
			get
			{
				return this._ValorConsumido;
			}
			set
			{
				if ((this._ValorConsumido != value))
				{
					this.OnValorConsumidoChanging(value);
					this.SendPropertyChanging();
					this._ValorConsumido = value;
					this.SendPropertyChanged("ValorConsumido");
					this.OnValorConsumidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeituraAtual", DbType="Float NOT NULL")]
		public double LeituraAtual
		{
			get
			{
				return this._LeituraAtual;
			}
			set
			{
				if ((this._LeituraAtual != value))
				{
					this.OnLeituraAtualChanging(value);
					this.SendPropertyChanging();
					this._LeituraAtual = value;
					this.SendPropertyChanged("LeituraAtual");
					this.OnLeituraAtualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeituraAnterior", DbType="Float NOT NULL")]
		public double LeituraAnterior
		{
			get
			{
				return this._LeituraAnterior;
			}
			set
			{
				if ((this._LeituraAnterior != value))
				{
					this.OnLeituraAnteriorChanging(value);
					this.SendPropertyChanging();
					this._LeituraAnterior = value;
					this.SendPropertyChanged("LeituraAnterior");
					this.OnLeituraAnteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContadorId", DbType="Int NOT NULL")]
		public int ContadorId
		{
			get
			{
				return this._ContadorId;
			}
			set
			{
				if ((this._ContadorId != value))
				{
					if (this._Contador.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnContadorIdChanging(value);
					this.SendPropertyChanging();
					this._ContadorId = value;
					this.SendPropertyChanged("ContadorId");
					this.OnContadorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Consumo_Fatura", Storage="_Faturas", ThisKey="Id", OtherKey="ConsumoId")]
		public EntitySet<Fatura> Faturas
		{
			get
			{
				return this._Faturas;
			}
			set
			{
				this._Faturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contador_Consumo", Storage="_Contador", ThisKey="ContadorId", OtherKey="Id", IsForeignKey=true)]
		public Contador Contador
		{
			get
			{
				return this._Contador.Entity;
			}
			set
			{
				Contador previousValue = this._Contador.Entity;
				if (((previousValue != value) 
							|| (this._Contador.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Contador.Entity = null;
						previousValue.Consumos.Remove(this);
					}
					this._Contador.Entity = value;
					if ((value != null))
					{
						value.Consumos.Add(this);
						this._ContadorId = value.Id;
					}
					else
					{
						this._ContadorId = default(int);
					}
					this.SendPropertyChanged("Contador");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Faturas(Fatura entity)
		{
			this.SendPropertyChanging();
			entity.Consumo = this;
		}
		
		private void detach_Faturas(Fatura entity)
		{
			this.SendPropertyChanging();
			entity.Consumo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nome;
		
		private string _Morada;
		
		private string _NIF;
		
		private string _Contacto;
		
		private string _Email;
		
		private string _CodigoPostal;
		
		private System.DateTime _Registo;
		
		private bool _Ativo;
		
		private EntitySet<Contador> _Contadors;
		
		private EntitySet<Fatura> _Faturas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnMoradaChanging(string value);
    partial void OnMoradaChanged();
    partial void OnNIFChanging(string value);
    partial void OnNIFChanged();
    partial void OnContactoChanging(string value);
    partial void OnContactoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCodigoPostalChanging(string value);
    partial void OnCodigoPostalChanged();
    partial void OnRegistoChanging(System.DateTime value);
    partial void OnRegistoChanged();
    partial void OnAtivoChanging(bool value);
    partial void OnAtivoChanged();
    #endregion
		
		public Cliente()
		{
			this._Contadors = new EntitySet<Contador>(new Action<Contador>(this.attach_Contadors), new Action<Contador>(this.detach_Contadors));
			this._Faturas = new EntitySet<Fatura>(new Action<Fatura>(this.attach_Faturas), new Action<Fatura>(this.detach_Faturas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Morada", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Morada
		{
			get
			{
				return this._Morada;
			}
			set
			{
				if ((this._Morada != value))
				{
					this.OnMoradaChanging(value);
					this.SendPropertyChanging();
					this._Morada = value;
					this.SendPropertyChanged("Morada");
					this.OnMoradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIF", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string NIF
		{
			get
			{
				return this._NIF;
			}
			set
			{
				if ((this._NIF != value))
				{
					this.OnNIFChanging(value);
					this.SendPropertyChanging();
					this._NIF = value;
					this.SendPropertyChanged("NIF");
					this.OnNIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contacto
		{
			get
			{
				return this._Contacto;
			}
			set
			{
				if ((this._Contacto != value))
				{
					this.OnContactoChanging(value);
					this.SendPropertyChanging();
					this._Contacto = value;
					this.SendPropertyChanged("Contacto");
					this.OnContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPostal", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string CodigoPostal
		{
			get
			{
				return this._CodigoPostal;
			}
			set
			{
				if ((this._CodigoPostal != value))
				{
					this.OnCodigoPostalChanging(value);
					this.SendPropertyChanging();
					this._CodigoPostal = value;
					this.SendPropertyChanged("CodigoPostal");
					this.OnCodigoPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registo", DbType="DateTime NOT NULL")]
		public System.DateTime Registo
		{
			get
			{
				return this._Registo;
			}
			set
			{
				if ((this._Registo != value))
				{
					this.OnRegistoChanging(value);
					this.SendPropertyChanging();
					this._Registo = value;
					this.SendPropertyChanged("Registo");
					this.OnRegistoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit NOT NULL")]
		public bool Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this.OnAtivoChanging(value);
					this.SendPropertyChanging();
					this._Ativo = value;
					this.SendPropertyChanged("Ativo");
					this.OnAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Contador", Storage="_Contadors", ThisKey="Id", OtherKey="ClienteId")]
		public EntitySet<Contador> Contadors
		{
			get
			{
				return this._Contadors;
			}
			set
			{
				this._Contadors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Fatura", Storage="_Faturas", ThisKey="Id", OtherKey="ClienteId")]
		public EntitySet<Fatura> Faturas
		{
			get
			{
				return this._Faturas;
			}
			set
			{
				this._Faturas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contadors(Contador entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Contadors(Contador entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_Faturas(Fatura entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Faturas(Fatura entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contador")]
	public partial class Contador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NumeroContador;
		
		private System.DateTime _DataInstalacao;
		
		private bool _Ativo;
		
		private int _ClienteId;
		
		private EntitySet<Consumo> _Consumos;
		
		private EntitySet<Fatura> _Faturas;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNumeroContadorChanging(string value);
    partial void OnNumeroContadorChanged();
    partial void OnDataInstalacaoChanging(System.DateTime value);
    partial void OnDataInstalacaoChanged();
    partial void OnAtivoChanging(bool value);
    partial void OnAtivoChanged();
    partial void OnClienteIdChanging(int value);
    partial void OnClienteIdChanged();
    #endregion
		
		public Contador()
		{
			this._Consumos = new EntitySet<Consumo>(new Action<Consumo>(this.attach_Consumos), new Action<Consumo>(this.detach_Consumos));
			this._Faturas = new EntitySet<Fatura>(new Action<Fatura>(this.attach_Faturas), new Action<Fatura>(this.detach_Faturas));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroContador", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NumeroContador
		{
			get
			{
				return this._NumeroContador;
			}
			set
			{
				if ((this._NumeroContador != value))
				{
					this.OnNumeroContadorChanging(value);
					this.SendPropertyChanging();
					this._NumeroContador = value;
					this.SendPropertyChanged("NumeroContador");
					this.OnNumeroContadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataInstalacao", DbType="DateTime NOT NULL")]
		public System.DateTime DataInstalacao
		{
			get
			{
				return this._DataInstalacao;
			}
			set
			{
				if ((this._DataInstalacao != value))
				{
					this.OnDataInstalacaoChanging(value);
					this.SendPropertyChanging();
					this._DataInstalacao = value;
					this.SendPropertyChanged("DataInstalacao");
					this.OnDataInstalacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit NOT NULL")]
		public bool Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this.OnAtivoChanging(value);
					this.SendPropertyChanging();
					this._Ativo = value;
					this.SendPropertyChanged("Ativo");
					this.OnAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteId", DbType="Int NOT NULL")]
		public int ClienteId
		{
			get
			{
				return this._ClienteId;
			}
			set
			{
				if ((this._ClienteId != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClienteIdChanging(value);
					this.SendPropertyChanging();
					this._ClienteId = value;
					this.SendPropertyChanged("ClienteId");
					this.OnClienteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contador_Consumo", Storage="_Consumos", ThisKey="Id", OtherKey="ContadorId")]
		public EntitySet<Consumo> Consumos
		{
			get
			{
				return this._Consumos;
			}
			set
			{
				this._Consumos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contador_Fatura", Storage="_Faturas", ThisKey="Id", OtherKey="ContadorId")]
		public EntitySet<Fatura> Faturas
		{
			get
			{
				return this._Faturas;
			}
			set
			{
				this._Faturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Contador", Storage="_Cliente", ThisKey="ClienteId", OtherKey="Id", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Contadors.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Contadors.Add(this);
						this._ClienteId = value.Id;
					}
					else
					{
						this._ClienteId = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Consumos(Consumo entity)
		{
			this.SendPropertyChanging();
			entity.Contador = this;
		}
		
		private void detach_Consumos(Consumo entity)
		{
			this.SendPropertyChanging();
			entity.Contador = null;
		}
		
		private void attach_Faturas(Fatura entity)
		{
			this.SendPropertyChanging();
			entity.Contador = this;
		}
		
		private void detach_Faturas(Fatura entity)
		{
			this.SendPropertyChanging();
			entity.Contador = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fatura")]
	public partial class Fatura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _DataFatura;
		
		private double _ValorTotal;
		
		private bool _Pago;
		
		private bool _Anulado;
		
		private int _ClienteId;
		
		private int _ContadorId;
		
		private int _ConsumoId;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Consumo> _Consumo;
		
		private EntityRef<Contador> _Contador;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDataFaturaChanging(System.DateTime value);
    partial void OnDataFaturaChanged();
    partial void OnValorTotalChanging(double value);
    partial void OnValorTotalChanged();
    partial void OnPagoChanging(bool value);
    partial void OnPagoChanged();
    partial void OnAnuladoChanging(bool value);
    partial void OnAnuladoChanged();
    partial void OnClienteIdChanging(int value);
    partial void OnClienteIdChanged();
    partial void OnContadorIdChanging(int value);
    partial void OnContadorIdChanged();
    partial void OnConsumoIdChanging(int value);
    partial void OnConsumoIdChanged();
    #endregion
		
		public Fatura()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Consumo = default(EntityRef<Consumo>);
			this._Contador = default(EntityRef<Contador>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataFatura", DbType="DateTime NOT NULL")]
		public System.DateTime DataFatura
		{
			get
			{
				return this._DataFatura;
			}
			set
			{
				if ((this._DataFatura != value))
				{
					this.OnDataFaturaChanging(value);
					this.SendPropertyChanging();
					this._DataFatura = value;
					this.SendPropertyChanged("DataFatura");
					this.OnDataFaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotal", DbType="Float NOT NULL")]
		public double ValorTotal
		{
			get
			{
				return this._ValorTotal;
			}
			set
			{
				if ((this._ValorTotal != value))
				{
					this.OnValorTotalChanging(value);
					this.SendPropertyChanging();
					this._ValorTotal = value;
					this.SendPropertyChanged("ValorTotal");
					this.OnValorTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pago", DbType="Bit NOT NULL")]
		public bool Pago
		{
			get
			{
				return this._Pago;
			}
			set
			{
				if ((this._Pago != value))
				{
					this.OnPagoChanging(value);
					this.SendPropertyChanging();
					this._Pago = value;
					this.SendPropertyChanged("Pago");
					this.OnPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anulado", DbType="Bit NOT NULL")]
		public bool Anulado
		{
			get
			{
				return this._Anulado;
			}
			set
			{
				if ((this._Anulado != value))
				{
					this.OnAnuladoChanging(value);
					this.SendPropertyChanging();
					this._Anulado = value;
					this.SendPropertyChanged("Anulado");
					this.OnAnuladoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteId", DbType="Int NOT NULL")]
		public int ClienteId
		{
			get
			{
				return this._ClienteId;
			}
			set
			{
				if ((this._ClienteId != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClienteIdChanging(value);
					this.SendPropertyChanging();
					this._ClienteId = value;
					this.SendPropertyChanged("ClienteId");
					this.OnClienteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContadorId", DbType="Int NOT NULL")]
		public int ContadorId
		{
			get
			{
				return this._ContadorId;
			}
			set
			{
				if ((this._ContadorId != value))
				{
					if (this._Contador.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnContadorIdChanging(value);
					this.SendPropertyChanging();
					this._ContadorId = value;
					this.SendPropertyChanged("ContadorId");
					this.OnContadorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumoId", DbType="Int NOT NULL")]
		public int ConsumoId
		{
			get
			{
				return this._ConsumoId;
			}
			set
			{
				if ((this._ConsumoId != value))
				{
					if (this._Consumo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnConsumoIdChanging(value);
					this.SendPropertyChanging();
					this._ConsumoId = value;
					this.SendPropertyChanged("ConsumoId");
					this.OnConsumoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Fatura", Storage="_Cliente", ThisKey="ClienteId", OtherKey="Id", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Faturas.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Faturas.Add(this);
						this._ClienteId = value.Id;
					}
					else
					{
						this._ClienteId = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Consumo_Fatura", Storage="_Consumo", ThisKey="ConsumoId", OtherKey="Id", IsForeignKey=true)]
		public Consumo Consumo
		{
			get
			{
				return this._Consumo.Entity;
			}
			set
			{
				Consumo previousValue = this._Consumo.Entity;
				if (((previousValue != value) 
							|| (this._Consumo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Consumo.Entity = null;
						previousValue.Faturas.Remove(this);
					}
					this._Consumo.Entity = value;
					if ((value != null))
					{
						value.Faturas.Add(this);
						this._ConsumoId = value.Id;
					}
					else
					{
						this._ConsumoId = default(int);
					}
					this.SendPropertyChanged("Consumo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contador_Fatura", Storage="_Contador", ThisKey="ContadorId", OtherKey="Id", IsForeignKey=true)]
		public Contador Contador
		{
			get
			{
				return this._Contador.Entity;
			}
			set
			{
				Contador previousValue = this._Contador.Entity;
				if (((previousValue != value) 
							|| (this._Contador.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Contador.Entity = null;
						previousValue.Faturas.Remove(this);
					}
					this._Contador.Entity = value;
					if ((value != null))
					{
						value.Faturas.Add(this);
						this._ContadorId = value.Id;
					}
					else
					{
						this._ContadorId = default(int);
					}
					this.SendPropertyChanged("Contador");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
